sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- cd ${TRAVIS_BUILD_DIR}/corona-diary-js
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
